# This configuration file stores information about every toolkits that we offer,
# and all the component's information, including it's version, description, and it's
# source URL.
# This file is used to generate toolkit-manifest (aka toolset-manifest) for each toolkit,
# also used to fetch component's package from web in order to pack the offline version,
# check cargo dev command for more details.
# This file is meant to be modified manually.
#
# 此配置文件存储了我们提供的所有工具包的信息，以及所有组件的信息，包括其版本、描述和源URL。
# 此文件用于为每个工具包生成 `toolkit-manifest`（又称 `toolset-manifest`），还用于从网络获取组件包，以便打包离线版本。
# 更多详情请查看 `cargo dev` 命令。
# 此文件需要手动修改。

[config]
rust-server = "https://xuanwu.base.atomgit.com"
rustup-server = "https://xuanwu.base.atomgit.com/rustup"
# The folder path (under `resources` dir) to store downloaded packages, used for offline packaging.
# package-dir = "packages"
targets = [
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]
components = [
    "cargo",
    "clippy",
    "rust-std",
    { name = "rust-docs", excluded-targets = [ "aarch64-unknown-linux-musl" ] },
    "rustc",
    "rustc-dev",
    "rustfmt",
    "llvm-tools",
    { name = "rust-mingw", target = "x86_64-pc-windows-gnu" },
    { name = "rust-src", wildcard-target = true },
]

# ========================= Manifest For Basic (test) Toolkit START =========================
[toolkit.basic.config]
date = "2024-09-05"

[toolkit.basic.value]
name = "XuanWu Rust Development Kit"
version = "stable v1.81.0"

[toolkit.basic.value.rust]
version = "1.81.0"
group = "Rust"
components = ["clippy", "rustfmt", "rust-src"]
optional-components = ["llvm-tools", "rustc-dev", "rust-docs"]

[toolkit.basic.value.rust.profile]
name = "minimal"
verbose-name = "Basic"
description = "Basic set of tools to use Rust properly"

[toolkit.basic.value.tools.descriptions]
llvm-tools = "Contains a collection of LLVM tools. Note that this component has not been stabilized and may change in the future and is provided as-is"
rustc-dev = "Contains the compiler as a library. Most users will not need this; it is only needed for development of tools that link to the compiler, such as making modifications to Clippy."
rust-docs = "A local copy of the Rust documentation. Allowing user to open the documentation in a web browser useing the `rustup doc` command"
mingw64 = "(windows only) Requirement for Windows GNU toolchain"

[toolkit.basic.value.tools.group]
Prerequisites = ["mingw64"]

[toolkit.basic.value.tools.target.x86_64-pc-windows-gnu]
mingw64 = { required = true, version = "14.2.0-rt_v12-rev0", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/x86_64-14.2.0-release-posix-seh-ucrt-rt_v12-rev0.7z" }
# ========================= Manifest For Basic (test) Toolkit END =========================

# ========================= Manifest For Community Toolkit START =========================
[toolkit.community.config]
date = "2025-01-30"
# These tools does not allow re-distribution
web-only = [ "buildtools", "vscode" ]

[toolkit.community.value]
name = "Rust 中国社区一站式开发套件"
version = "stable v1.84.1"

[toolkit.community.value.rust]
version = "1.84.1"
group = "Rust 基础工具集"
components = ["clippy", "rustfmt", "rust-src"]
optional-components = ["llvm-tools", "rustc-dev", "rust-docs", "rust-analyzer"]

[toolkit.community.value.rust.profile]
name = "minimal"
verbose-name = "Rust 官方工具"
description = "Rust 官方工具链，包含 rustc (编译器), rust-std (标准库), cargo (包管理) 等工具"

[toolkit.community.value.tools.descriptions]
llvm-tools = "包含 LLVM 工具的集合"
rustc-dev = "将编译器作为库来内部 API。大多数用户不需要这个; 仅当开发链接到编译器的工具时才需要它, 例如对 Clippy 进行修改"
rust-docs = "本地 Rust 文档副本，允许用户使用 rustup doc 命令在 Web 浏览器中打开文档"
rust-analyzer = "Rust 编程语言的 语言服务器协议 (LSP) 实现。注: 这是 rust-analyzer 的服务端, 若需要在编辑器 (如 VS Code) 中使用其代码补全、跳转到定义等功能, 只需选择列表中相应的编辑器插件即可。"
mingw64 = "编译器在 x86_64 Windows GNU 环境下的依赖组件"
typos = "源代码拼写检查器，用于查找并纠正源代码中的拼写错误"
cargo-nextest = "新一代 Rust 项目测试运行程序，相比传统 cargo test 而言更快速，界面更简洁明了"
vscode = "Visual Studio Code (简称 VS Code) 将代码编辑器的简洁性与开发者核心的 编辑-构建-调试 流程相结合。它提供全面的代码编辑、导航和理解支持，同时具备轻量级调试功能、丰富的扩展模型，并可与现有工具无缝集成，提升开发效率。"
vscodium = "一个由社区维护的、采用自由许可的 VS Code 二进制发行版 —— 基于微软开源的 VS Code 源代码（MIT 许可），但去除了微软的品牌标识和遥测功能，提供了一个完全开源、无数据追踪的开发环境，适用于希望避免微软官方构建限制的用户。"
codearts-rust = "CodeArts IDE 定位华为云开发者桌面，是利用自主可控技术内核，面向华为云开发者提供的智能化可扩展桌面集成开发环境（IDE），结合华为云行业和产业开发套件，实现极致的一站式用云和开发体验。"
"rust-analyzer (VS Code 插件)" = "Rust 编程语言的 语言服务器协议 (LSP) 实现。为 VS Code 编辑器 (包括其衍生编辑器, 例如 VSCodium 等) 提供代码补全、跳转到定义等功能，提升 Rust 开发体验。"

[toolkit.community.value.tools.group]
"Rust 基础工具集" = ["mingw64"]
"Rust 优选工具集" = ["typos", "cargo-nextest"]
"Rust 软件开发工具链" = ["vscode", "vscodium", "codearts-rust", "rust-analyzer (VS Code 插件)"]

[toolkit.community.value.tools.target.x86_64-pc-windows-gnu]
mingw64 = { required = true, version = "14.2.0-rt_v12-rev0", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/x86_64-14.2.0-release-posix-seh-ucrt-rt_v12-rev0.7z" }
vscodium = { version = "1.97.2.25045", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/codium/VSCodium-win32-x64-1.97.2.25045.zip" }
"rust-analyzer (VS Code 插件)" = { version = "0.3.2299", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/rust-analyzer/0.3.2299/rust-analyzer-win32-x64.vsix" }
cargo-nextest = { optional = true, version = "0.9.91", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/cargo-nextest/cargo-nextest-0.9.91-x86_64-pc-windows-msvc.zip" }
typos = { optional = true, version = "1.29.7", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/typos/typos-v1.29.7-x86_64-pc-windows-msvc.zip" }

[toolkit.community.value.tools.target.x86_64-pc-windows-msvc]
vscodium = { version = "1.97.2.25045", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/codium/VSCodium-win32-x64-1.97.2.25045.zip" }
"rust-analyzer (VS Code 插件)" = { version = "0.3.2299", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/rust-analyzer/0.3.2299/rust-analyzer-win32-x64.vsix" }
cargo-nextest = { optional = true, version = "0.9.91", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/cargo-nextest/cargo-nextest-0.9.91-x86_64-pc-windows-msvc.zip" }
typos = { optional = true, version = "1.29.7", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/typos/typos-v1.29.7-x86_64-pc-windows-msvc.zip" }

[toolkit.community.value.tools.target.x86_64-unknown-linux-gnu]
# Make vscode optional on Linux, because not everyone has desktop environment, we might add such check later but entil then, this is the safetest option
vscodium = { optional = true, version = "1.97.2.25045", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/codium/VSCodium-linux-x64-1.97.2.25045.tar.gz" }
"rust-analyzer (VS Code 插件)" = { optional = true, version = "0.3.2299", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/rust-analyzer/0.3.2299/rust-analyzer-linux-x64.vsix" }
cargo-nextest = { optional = true, version = "0.9.91", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/cargo-nextest/cargo-nextest-0.9.91-x86_64-unknown-linux-gnu.tar.gz" }
typos = { optional = true, version = "1.29.7", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/typos/typos-v1.29.7-x86_64-unknown-linux-musl.tar.gz" }

[toolkit.community.value.tools.target.aarch64-unknown-linux-gnu]
vscodium = { optional = true, version = "1.97.2.25045", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/codium/VSCodium-linux-arm64-1.97.2.25045.tar.gz" }
"rust-analyzer (VS Code 插件)" = { optional = true, version = "0.3.2299", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/rust-analyzer/0.3.2299/rust-analyzer-linux-arm64.vsix" }
cargo-nextest = { optional = true, version = "0.9.91", url = "https://rust-mirror.obs.cn-north-4.myhuaweicloud.com/dist/toolset/cargo-nextest/cargo-nextest-0.9.91-aarch64-unknown-linux-gnu.tar.gz" }
typos = { optional = true, ver = "1.29.7", identifier = "typos-cli" }
# ========================= Manifest For Community Toolkit END =========================
