name: GUI Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'rim_gui/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'rim_gui/**'

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  gui-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: bash ci/scripts/install-tauri-deps.sh

      - name: run clippy
        run: cargo clippy --no-deps -p rim-gui -- -D warnings
      - name: run tests
        run: cargo test -p rim-gui --verbose
