name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag name
  push:
    tags:
      - v*.*.*

jobs:
  release:
    name: "Job - ${{ matrix.name }}"
    runs-on: "${{ matrix.os }}"
    env:
      EDITION: community
    
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: dist-aarch64-linux-musl
            os: ubuntu-22.04-arm
            build-target: aarch64-unknown-linux-musl
            dist-targets: aarch64-unknown-linux-gnu

          - name: dist-x86-64-linux-musl
            os: ubuntu-22.04
            build-target: x86_64-unknown-linux-musl
            dist-targets: x86_64-unknown-linux-gnu

          - name: dist-windows-msvc
            os: windows-latest
            build-target: x86_64-pc-windows-msvc
            dist-targets: x86_64-pc-windows-msvc,x86_64-pc-windows-gnu

    steps:
      - name: checkout the source code
        uses: actions/checkout@v4

      - name: setup node (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable (Windows)
        if: matrix.os == 'windows-latest'
        uses: dtolnay/rust-toolchain@stable

      - name: install tauri deps (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          npm install -g pnpm
          bash ci/scripts/install-tauri-cli.sh

      - name: run build job (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cargo dev vendor --for ${{ matrix.dist-targets }}
          cargo dev dist --target ${{ matrix.build-target }} --for ${{ matrix.dist-targets }}

      - name: run build job (Linux)
        if: matrix.os != 'windows-latest'
        run: bash ci/scripts/linux-dist.sh --image ${{ matrix.name }}

      - name: upload release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: "./dist/*"
          prerelease: true
