name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag name
  push:
    tags:
      - v*.*.*

jobs:
  release:
    name: "Job - ${{ matrix.name }}"
    runs-on: "${{ matrix.os }}"
    env:
      EDITION: community
    
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: dist-aarch64-linux-musl
            os: ubuntu-22.04-arm
            build-target: aarch64-unknown-linux-musl
            dist-targets: aarch64-unknown-linux-gnu

          - name: dist-x86-64-linux-musl
            os: ubuntu-20.04
            build-target: x86_64-unknown-linux-musl
            dist-targets: x86_64-unknown-linux-gnu

          - name: dist-windows-msvc
            os: windows-latest
            build-target: x86_64-pc-windows-msvc
            dist-targets: x86_64-pc-windows-msvc,x86_64-pc-windows-gnu

    steps:
      - name: checkout the source code
        uses: actions/checkout@v4

      - name: install dependencies (Linux)
        if: matrix.os != 'windows-latest'
        run: |
          bash ci/scripts/install-tauri-deps.sh
          sudo apt-get install -y musl-tools

      - name: setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install pnpm
        run: npm i -g pnpm

      - name: install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.build-target }}

      - name: download packages for offline build
        run: cargo dev vendor --for ${{ matrix.dist-targets }}

      - name: run build job (musl)
        if: contains(matrix.build-target, 'musl')
        run: |
          cargo dev dist --cli --target ${{ matrix.build-target }} --for ${{ matrix.dist-targets }}
          cargo dev dist --gui --for ${{ matrix.dist-targets }}

      - name: run build job
        if: ${{ !contains(matrix.build-target, 'musl') }}
        run: cargo dev dist --target ${{ matrix.build-target }} --for ${{ matrix.dist-targets }}

      - name: upload release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: "./dist/*"
          prerelease: true
