name: Standard Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  basic-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-latest'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: install rustup & toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: formatting check
      run: cargo fmt --all --check
    - name: build
      run: cargo build --workspace --exclude rim-gui --verbose
    - name: clippy check
      run: cargo clippy --no-deps --workspace --exclude rim-gui -- -D warnings
    - name: run tests
      run: cargo test --workspace --exclude rim-gui --verbose
  
  try-build:
    env:
      CI_JOB_NAME: "${{ matrix.name }}"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: dist-x86-64-linux-gnu
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

          - name: dist-windows-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc
            target-gnu: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: run build job
        run: bash ci/run.sh
